openapi: 3.0.1
info:
  title: teste
  description: API Definition of teste
  version: 1.0.0
servers:
- url: http://localhost:8290/teste
paths:
  /:
    get:
      responses:
        default:
          description: Default response
